# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#


version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  node: circleci/node@4.5.2
     
working_directory: /tmp

# Define the jobs we want to run for this project
jobs:
  build-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
       - checkout
       - run: |
           ls -al
       - node/install:
          node-version: '12.8.0' 
       - run: |
            export NODE_OPTIONS=--max_old_space_size=4096
       - run: npm i
       #- run: node --version
       #- run: node ./node_modules/@angular/cli/bin/ng build --prod --progress
       #- run: |
       #    ls -al
       - slack/status:
           fail_only: false
           webhook: $SLACK_ADMIN_WEBHOOK


# Orchestrate our job run sequence
workflows:
  build_and_deploy:
    jobs:
      - build-job